Added Boundaries input field (geoJson) in create/update stations and  create/update services
TaskarCenterAtUW/TDEI-user-management-front-end pull request #40
Opened 2023-10-20 10:44 UTC by shweta2101

### Overview of Changes Implemented : 
- Replaced create/update stations and create/update services modals with a dedicated screen which takes in station/service name and Service/Stations Boundaries (Geo Json) as inputs.

- Create Service/Station Scenario:
 
     - Upon clicking create Service/Stations button, user can enter the name (which is a required field) and also, the boundaries field which by default displays expected Geo Json format which in turn can be edited or replaced by a valid Geo Json. 
 - Update Service/Station Scenario:
 
      - Upon clicking update Service/Stations button, user can edit the name (which is a required field) and also, the boundaries field which by default displays previously entered Geo Json which in turn can be edited or replaced by a valid Geo Json. 
 - Geo Json can be generated and copy pasted in the text area using [geojson.io](http://geojson.io/).  
 - While updating or creating a Service/Station, if the starting and ending coordinates of the geoJson do not match, it throws an error, which is displayed in the form of a toast.
- Screenshots : 
<img width="1470" alt="Screenshot 2023-10-20 at 12 38 25 PM" src="https://github.com/TaskarCenterAtUW/TDEI-user-management-front-end/assets/142565248/d9d21ec7-1c8f-493a-8877-0d214187d08d">

<img width="1470" alt="Screenshot 2023-10-20 at 12 39 39 PM" src="https://github.com/TaskarCenterAtUW/TDEI-user-management-front-end/assets/142565248/e6a7834a-0eac-4c36-bb8c-26f2bbd501c2">

<img width="1470" alt="Screenshot 2023-10-20 at 12 39 05 PM" src="https://github.com/TaskarCenterAtUW/TDEI-user-management-front-end/assets/142565248/72951ac9-fabf-47ac-a6d7-1dc3cd7a3f52">

<img width="1470" alt="Screenshot 2023-10-20 at 12 41 08 PM" src="https://github.com/TaskarCenterAtUW/TDEI-user-management-front-end/assets/142565248/4dd22996-e42e-4d54-b53a-c1c19a6dfe0c">

<img width="1470" alt="Screenshot 2023-10-20 at 12 41 40 PM" src="https://github.com/TaskarCenterAtUW/TDEI-user-management-front-end/assets/142565248/3449f75c-0962-4119-99ad-8588bfaae561">

2023-10-20 11:09 UTC, MashB requested changes

2023-10-20 12:18 UTC, shweta2101 commented on tdei-ui/src/routes/Stations/CreateUpdateStation.js
> +            console.log("geoJson", geoJson);
Removed console logs.

2023-10-20 12:21 UTC, shweta2101 commented on tdei-ui/package.json
> +    "@emotion/react": "^11.11.1",
These were earlier used to cater Mapbox UI needs. As we've now removed that functionality, material library is no longer needed. Removed material library related code. There is no change in UI (as seen in screenshots) after the removal of material library.

2023-10-23 06:02 UTC, MashB approved these changes

2023-10-25 06:40 UTC, susrisha approved these changes

2023-10-25 06:40 UTC, merged