TDEI branding changes
TaskarCenterAtUW/TDEI-user-management-front-end pull request #97
Opened 2024-07-22 16:21 UTC by faizm21

2024-07-22 21:39 UTC, sureshgaussian requested changes
Could you add notes to readme.md on how one can change colors/fonts if necessary and test those locally? UW wants to adjust the colors as they feel they should be using different colors. They will update their design/branding guidelines document as well.

2024-07-23 04:18 UTC, faizm21 commented
> Could you add notes to readme.md on how one can change colors/fonts if necessary and test those locally? UW wants to adjust the colors as they feel they should be using different colors. They will update their design/branding guidelines document as well.

Readme.md file updated.

2024-07-23 16:33 UTC, sureshgaussian requested changes

2024-07-23 16:33 UTC, sureshgaussian commented on README.md
>  REACT_APP_MAP_KEY= <Map API Key for mapbox>
do we still need this?

2024-07-23 17:11 UTC, faizm21 commented on README.md
>  REACT_APP_MAP_KEY= <Map API Key for mapbox>
Removed REACT_APP_MAP_KEY

2024-07-23 17:16 UTC, sureshgaussian approved these changes
lets go ahead and merge

2024-07-23 17:16 UTC, merged